
  name: league-of-legends
  version: '0.1'
  summary: Play League Of Legends in a snap.
  description: |
    This snap will enable you to play League of Legends on Linux with a simple snap install.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    league-of-legends:
    plugin: dump
    build-attributes: [no-patchelf]
    build-packages:
    - curl
    - openssl
    - file
    stage-packages:
    - conntrack
    - docker.io
    - aufs-tools
    - gawk
    source: .
    override-build: |
      set -eu
      docker build -t lol:latest .
      snapcraftctl build
  
